name: pmd

on:
  push:
    branches:
      - '*'

permissions:
  contents: read
  security-events: write
  actions: write

jobs:
  pmd:
    name: Run PMD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run PMD
        uses: pmd/pmd-github-action@v2
        with:
          version: '7.0.0-rc4'
          sourcePath: 'src/main/java'
          rulesets: 'rulesets/java/quickstart.xml'
          analyzeModifiedFilesOnly: false

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sarif-file
          path: pmd-report.sarif
          retention-days: 5

